# Generated by Django 3.0.1 on 2019-12-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('mainCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('mainCategoryTitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unitId', models.AutoField(primary_key=True, serialize=False)),
                ('unitTitle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('subCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('subCategoryTitle', models.CharField(max_length=100)),
                ('mainCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Main_Category')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryId', models.AutoField(primary_key=True, serialize=False)),
                ('inventoryName', models.CharField(max_length=100)),
                ('inventoryDesc', models.TextField()),
                ('mainCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Main_Category')),
                ('subCatId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Sub_Category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Unit')),
            ],
        ),
    ]
